"""
Main application entry point.

Run locally with:
    uvicorn app.main:app --reload

Interactive API docs (auto-generated by FastAPI) will be at:
    http://localhost:8000/docs
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.core.config import settings
from app.db.session import Base, engine
import app.models  # noqa: F401 -- registers all models with Base.metadata
from app.routers import auth, users, patients, visits

# Creates all tables if they don't already exist. Fine for a project like
# this; a production system would use a migration tool (Alembic) instead
# so schema changes are tracked and reversible.
Base.metadata.create_all(bind=engine)

app = FastAPI(
    title=settings.app_name,
    description="Electronic Health Records system for a Kenyan hospital.",
    version="0.1.0",
)

# Allows the React dev server (typically on localhost:5173 or :3000) to
# call this API. In production, restrict allow_origins to the real
# frontend domain instead of using a wildcard.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth.router)
app.include_router(users.router)
app.include_router(patients.router)
app.include_router(visits.router)


@app.get("/")
def root():
    return {"status": "ok", "service": settings.app_name}


@app.get("/health")
def health_check():
    return {"status": "healthy"}
